[build]
publish = "public"
command = "hugo --minify --gc"

[build.environment]
HUGO_VERSION = "0.98.0"

HUGO_BASEURL = "/"  #solution for error sitemap.xml "/", delete this line , using external css/js if via CDN if css/js doesnt work .

[[headers]]
for = "/*" 

[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "your policy"
Cache-Control = "public, max-age=31536000"
